### PR TITLE
Unlinked concepts

### PR DESCRIPTION
**Pull request by Schweikhard**
Took care of most in https://github.com/clld/concepticon-data/issues/568

### CODE REVIEW

**Comment by LinguList** [comment]
sorry for the numerous comments, but I consider them important. Especially meadow and water.

**Comment by Schweikhard** [comment]
Thanks!
Huh, that should actually be IRRIGATE - the ID was correct, though, so I wonder why no conflict was found?

**Comment by xrotwang** [comment]
@Schweikhard there was no such test so far. I just added one and found these cases where CONCEPTICON_GLOSS does not match CONCEPTICON_ID:
```
ERROR:Castro-2015-608: wrong conceptset GLOSS for ID 191: CHILI PEPPER -> NUT
ERROR:Castro-2015-608: wrong conceptset GLOSS for ID 2398: FLAVOR -> MANGO
ERROR:Castro-2015-608: wrong conceptset GLOSS for ID 1453: None -> WASH
ERROR:Castro-2015-608: wrong conceptset GLOSS for ID 278: FIRST -> AWL
ERROR:Hill-2017-240: wrong conceptset GLOSS for ID 363: RESIDE -> DWELL (LIVE, RESIDE)
ERROR:Dellert-2017-1016: wrong conceptset GLOSS for ID 262: HE -> HE OR SHE OR IT
ERROR:Bowern-2012-644: wrong conceptset GLOSS for ID 1826: VAGINA -> ANGRY
ERROR:Kingsada-1999-303: wrong conceptset GLOSS for ID 191: CHILI PEPPER -> NUT
ERROR:BeijingDaxue-1964-905: wrong conceptset GLOSS for ID 1266: WALKING STICK -> BRIDE
ERROR:BeijingDaxue-1964-905: wrong conceptset GLOSS for ID 2171: AUNT -> PATERNAL AUNT (WIFE OF FATHER'S YOUNGER BROTHER)
ERROR:Chacon-2014-142: wrong conceptset GLOSS for ID 98: YOU -> ALL
ERROR:Blust-1981-200: wrong conceptset GLOSS for ID 2643: HE OR SHE -> INK
ERROR:Key-2016-1310: wrong conceptset GLOSS for ID 3199: GUESS -> TWIST (AROUND)
ERROR:SatterthwaitePhillips-2011-423: wrong conceptset GLOSS for ID 676: FAECES (EXCREMENT) -> SHIT (DEFECATE)
ERROR:Galucio-2015-90: wrong conceptset GLOSS for ID 2443: CRICKET -> ELECTRIC EEL
ERROR:Davies-1985-116: wrong conceptset GLOSS for ID 4: AXE -> COURTYARD
```

**Comment by xrotwang** [comment]
@Schweikhard @LinguList should we roll fixes for the issues above into this PR and merge today?

**Comment by Schweikhard** [comment]
With my PR on Monday there was such a test.
I'll fix the mistakes.

**Comment by chrzyki** [comment]
Heads up, I resolved the conflict with the list ID changes (https://github.com/clld/concepticon-data/pull/582) in your master.

**Comment by xrotwang** [comment]
Ok, we are down to these now:
```
ERROR:Hill-2017-240: wrong conceptset GLOSS for ID 363: RESIDE -> DWELL (LIVE, RESIDE)
ERROR:Bowern-2012-644: wrong conceptset GLOSS for ID 1826: VAGINA -> ANGRY
ERROR:Kingsada-1999-303: wrong conceptset GLOSS for ID 191: CHILI PEPPER -> NUT
ERROR:BeijingDaxue-1964-905: wrong conceptset GLOSS for ID 1266: WALKING STICK -> BRIDE
ERROR:BeijingDaxue-1964-905: wrong conceptset GLOSS for ID 2171: AUNT -> PATERNAL AUNT (WIFE OF FATHER'S YOUNGER BROTHER)
ERROR:Chacon-2014-142: wrong conceptset GLOSS for ID 98: YOU -> ALL
ERROR:Blust-1981-200: wrong conceptset GLOSS for ID 2643: HE OR SHE -> INK
ERROR:Key-2016-1310: wrong conceptset GLOSS for ID 3199: GUESS -> TWIST (AROUND)
ERROR:Galucio-2015-90: wrong conceptset GLOSS for ID 2443: CRICKET -> ELECTRIC EEL
ERROR:Davies-1985-116: wrong conceptset GLOSS for ID 4: AXE -> COURTYARD
```

**Comment by LinguList** [comment]
Ah, I thought this was covered, but in fact, we have a REMAP procedure, right? This takes the ID OR the GLOSSS and remaps them in a list. This is what helped me to avoid errors in my submissions.

**Comment by LinguList** [comment]
Okay, so @Schweikhard, send me an email if your down there, and I'll look into lexibank in the meantime.

**Comment by xrotwang** [comment]
@LinguList but how is remap to decide whether ID or GLOSS is correct? Prefer ID?

**Comment by Schweikhard** [comment]
I've fixed the mistakes you pointed out @xrotwang - could you check again?

**Comment by LinguList** [comment]
> @LinguList but how is remap to decide whether ID or GLOSS is correct? Prefer ID?

well, it was not necessarily this, but would add the gloss if you left something empty. So you add GLOSS it adds ID, you add ID it adds GLOSS.

**Comment by xrotwang** [comment]
@Schweikhard yes. looks goo. Will merge now, and then release pyconcepticon with the additional checks.

**Comment by LinguList** [comment]
@xrotwang don't merge!

**Comment by Schweikhard** [comment]
There are some mistakes mattis pointed out that I haven't fixed yet since Github doesn't show me his comments.

**Comment by LinguList** [comment]
There are problems in the linkings, I'll send a list now.

**Comment by LinguList** [comment]
sorry, I forgot to SUBMIT the `***` review, so you other people never saw my comments from yesterday...

**Comment by xrotwang** [comment]
@Schweikhard @LinguList the comments here: https://github.com/clld/concepticon-data/pull/581/commits/8040dfe57766a96a82207ebe5539c03563a7913e ?
Ok. I'll leave the merging to @LinguList  then.

**Comment by LinguList** [comment]
Summarizing now:

* [ ] Allen-2007-500-19: GRASSLAND
* [ ] Allen-2007-500-93: SWIDDEN FIELD (mapping WAS correct)
* [ ] Bulakh-2013-870-143: Link to BUD
* [ ] Bulakh-2013-870-144: Link to BUD
* [ ] Bulakh-2013-870-164: link to HARD
* [ ] Bulakh-2013-870-188: FINISH
* [ ] Castro-2015-608-349: WASH 
* [ ] Dellert-2017-1016-822: *PUT (UPRIGHT POSITION)
* [ ] Dellert-2017-1016-823: *PUT (SEATING POSITION)
* [ ] Dellert-2017-1016-824: *PUT (LYING POSITION)
* [ ] Mitterhofer-2013-300-300: FINISH

**Comment by LinguList** [comment]
Just summarized in the checklist. I consider these important.

**Comment by LinguList** [comment]
@Schweikhard, the `*PUT` is not that important, but the other cases are, I guess, so I'll wait until you rewind them and will merge then. Thanks, and sorry for requesting so many things...

**Comment by Schweikhard** [comment]
I fixed what I think should be fixed and answered your email about the rest.

**Comment by LinguList** [comment]
didn't receive any email.

**Comment by Schweikhard** [comment]
Sorry, now you should.

**Comment by LinguList** [comment]
and please check the cases you fixed, so I can compare. I don't see Allen GRASSLAND, but the concept IS grassland, the Chinese term is pointing to this, etc. you see?

**Comment by LinguList** [comment]
So I am referring to the check list items, which are the condensed form of my requests.

**Comment by LinguList** [comment]
Please also note that cases like the list of the Russians on semantic shift, Bulakh, are in fact collections that would have profited from concepticon, so their definitions should NOT be taken literally, so we can allow for more mergers. That's why BUD can be linked twice. You always need to take the history of the list into account.

**Comment by LinguList** [comment]
This word means "Wiese, Rasen" in Chinese, www.handedict.de/chinesisch_deutsch.php?sid=ae7ea4c8f108a4b1f020319af13197fe
It is mis-spelled, as they use a slightly different character (lookalike). So you could then link Allen to pasture.

**Comment by LinguList** [comment]
For the swidden /paddy: we have paddy field, so you should not just unlink, but add the new link, right?

**Comment by Schweikhard** [comment]
> This word means "Wiese, Rasen" in Chinese, [www.handedict.de/chinesisch_deutsch.php?sid=ae7ea4c8f108a4b1f020319af13197fe](http://www.handedict.de/chinesisch_deutsch.php?sid=ae7ea4c8f108a4b1f020319af13197fe)
> It is mis-spelled, as they use a slightly different character (lookalike). So you could then link Allen to pasture.

Can't see which you are referring to. 
You mean 旱地?
Yunfan said this is a field were crops are grown without access to irrigation (besides rain).

> For the swidden /paddy: we have paddy field, so you should not just unlink, but add the new link, right?

As I wrote, paddy field is already at another place in the same list.
And according to Wikipedia at least, 水稻 refers to the paddy rice plant, not the field.

**Comment by LinguList** [comment]
> And according to Wikipedia at least, 水稻 refers to the paddy rice plant, not the field.
I checked this now. The English translation is wrong, and in fact, the Bai word (which also needs to be checked here) is the Chinese tterm for "Wasserreis", so you're right. Well spotted!

**Comment by Schweikhard** [comment]
> Please also note that cases like the list of the Russians on semantic shift, Bulakh, are in fact collections that would have profited from concepticon, so their definitions should NOT be taken literally, so we can allow for more mergers. That's why BUD can be linked twice. You always need to take the history of the list into account.

I don't know whether they were consistent, but they do seem to distinguish between tree buds and flower buds on http://datsemshift.ru/meanings/b

> > And according to Wikipedia at least, 水稻 refers to the paddy rice plant, not the field.
> I checked this now. The English translation is wrong, and in fact, the Bai word (which also needs to be checked here) is the Chinese tterm for "Wasserreis", so you're right. Well spotted!
I'll link it to RICE PLANT then.

**Comment by LinguList** [comment]
> 旱地

Interesting, again, looking at the original data, this may make sense, although I never heard the term, and was just thinking it was cǎo dì, a term referring to grass. So again, good that you asked. The original data confirms your mapping.

**Comment by LinguList** [comment]
> I don't know whether they were consistent, but they do seem to distinguish between tree buds and flower buds on http://datsemshift.ru/meanings/b

This is a new version of the data, by other authors. They may be more consistent, the old version was not, and is no longer online.

**Comment by LinguList** [comment]
Which actually shows we should start adding their new data  soon!

**Comment by Schweikhard** [comment]
Oh, didn't know it was different data. 

I'd agree linking the "hard" and "flow" duplicates to both, but with the rest I'm a bit reluctant.

**Comment by LinguList** [comment]
It's not that important. The two remaining issues, I'd like to reconsider are:

* get up (in Satterthwaite-Phillips)
* cease etc. in Mitterhofer

Why so? Both lists are important for us, so the more concepts we have mapped, the better. The "stop doing" occurs twice, so either linking it to cease is useful, or adding a new concept.
Same for "get up": this concept occurs in two lists, it is a very common concept, and I'd like to have as much as possible linked of Satterthwaite's data.

**Comment by LinguList** [comment]
Castro's WASH as well. I don't think it is meaning "wash clothes only" I think, it means "wash (e.g., clothes)". We could even write an email to Andy and ask him.

**Comment by Schweikhard** [comment]
Okay, I'll add new concepts for GET UP FROM BED and STOP DOING.

**Comment by Schweikhard** [comment]
Castro differentiates between "to wash (hands, dishes)" and "to wash (clothes)". Hm, we could link the latter to LAUNDER.
https://concepticon.clld.org/parameters/2503

**Comment by Schweikhard** [comment]
Done!

**Pull request merged**
