### PR TITLE
Tidy and standardise bibtex file

### PR DESCRIPTION
**Pull request by SimonGreenhill**
Make format more consistent.

### CODE REVIEW

**Comment by xrotwang** [comment]
@SimonGreenhill can we make sure, this format is always kept - e.g. running something like [BibTool](http://www.gerd-neugebauer.de/software/TeX/BibTool/en/) before commit?

**Comment by SimonGreenhill** [comment]
Oh god what is with that website?

**Comment by xrotwang** [comment]
the tool is ok, though :)

**Comment by xrotwang** [comment]
right. This looks ok to me - certainly reproducible.

**Comment by SimonGreenhill** [comment]
perhaps a new command? format_bib?

**Comment by SimonGreenhill** [comment]
Ok, the customisations allowed are:

```python
        #: List of BibTeX elements to write, valid values are `entries`, `comments`, `preambles`, `strings`.
        self.contents = ['comments', 'preambles', 'strings', 'entries']
        #: Character(s) for indenting BibTeX field-value pairs. Default: single space.
        self.indent = ' '
        #: Align values. Determines the maximal number of characters used in any fieldname and aligns all values
        #    according to that by filling up with single spaces. Default: False
        self.align_values = False
        #: Characters(s) for separating BibTeX entries. Default: new line.
        self.entry_separator = '\n'
        #: Tuple of fields for ordering BibTeX entries. Set to `None` to disable sorting. Default: BibTeX key `('ID', )`.
        self.order_entries_by = ('ID', )
        #: Tuple of fields for display order in a single BibTeX entry. Fields not listed here will be displayed
        #: alphabetically at the end. Set to '[]' for alphabetical order. Default: '[]'
        self.display_order = []
        #: BibTeX syntax allows comma first syntax
        #: (common in functional languages), use this to enable
        #: comma first syntax as the bwritter output
        self.comma_first = False
        #: internal variable used if self.align_values = True
        self._max_field_width = 0
        #: Whether common strings are written
        self.common_strings = write_common_strings
```

I think self.indent should be two spaces, self.align_values should be True, write_common_strings should be True (this outputs month as "june" etc). 

Anything else?  @LinguList ?

**Pull request merged**
