### PR TITLE
update northeuralex, add data to concepticon

### PR DESCRIPTION
**Pull request by LinguList**
I changed some further instances, also refining one concept set which still remained with a comma. There are borderline-cases, like "SINK" which is now split inot two concepts, one meaning German "versinken" one "sinken". But in this way, we do justice to NELEX. 

I started using Merriam-Webster to create definitions. This is why I also added it as metadata. I also wrote a custom-script to pull wikipedia definitions. If data keeps increasing in terms of new concept sets at a fast pace, we may consider adding something like this to the Concepticon API. But I don't expect similar bursts in the nearer future.

### CODE REVIEW

**Comment by xrotwang** [comment]
@LinguList are you going to fix this: https://travis-ci.org/clld/concepticon-data/builds/247657871#L535

**Comment by LinguList** [comment]
sure, didn't see it as it runs without errors with me

**Comment by LinguList** [comment]
ah, I see it, forgot to push concepticon.tsv.

**Comment by LinguList** [comment]
We need to make sure to report back to the nelex people. They could by now refine the concepticon-mappings, and would ideally provide us with the urls, so we can link from concepticon. I'll also add them to the list of contributors.

**Comment by LinguList** [comment]
okay, pushed this as well, so they are now also listed as contributors.

**Comment by xrotwang** [comment]
Still fails, though: https://travis-ci.org/clld/concepticon-data/builds/247663641#L535

**Comment by LinguList** [comment]
grrr, on it, one second.

**Comment by LinguList** [comment]
strange that ```Concepticon test``` does not report this issue...

**Comment by xrotwang** [comment]
Hm. That is strange. We should look into this. maybe the test is looking at files not under version control?

**Pull request merged**
