### PR TITLE
Documentation Improvements

### PR DESCRIPTION
**Pull request by chrzyki**
Just a little something to improve the documentation of commands that are directly available to end-users.

### CODE REVIEW

**Comment by chrzyki** [comment]
Ah, alright! Will change this then! Thanks for pointing this out.

**Comment by xflr6** [comment]
Here are some examples (I prefer the former markup variant):
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html

There is also [pep-257](https://www.python.org/dev/peps/pep-0257/)

**Comment by LinguList** [comment]
My favorit is numpy, as we use it also for lingpy.

**Comment by chrzyki** [comment]
And another attempt.

**Pull request merged**
