### PR TITLE
Dye et al 1968

### PR DESCRIPTION
**Pull request by SimonGreenhill**

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
Note: missing term for "sago thatch"

**Comment by LinguList** [comment]
Is this something that occurs frequently, a sago thatch? We currently allow for very specified concepts to be missing (as you'll know), the policy being to add a new concept with definition if it is likely that it may occur in other lists.

**Comment by SimonGreenhill** [comment]
sure, but I've got it two other lists -- Fleischmann and Turpeinen 1976, and Staalsen 1969

**Comment by LinguList** [comment]
so let's add it. Increment the ID, define it's semantic field, make a short definition (maybe just the one from wikipedia), and that's it. You can actually use the same semantic field as for "thatch" (or not?):

```text
279	THATCH	The house	Natural roofing material such as straw, reeds, leaves, etc.	Person/Thing
```

So using this as a role model.

**Comment by LinguList** [comment]
Hi @SimonGreenhill, so do you plan on adding the new concept set, or should we deal with it afterwards?

**Comment by SimonGreenhill** [comment]
Not sure -- I think it's just thatching using sago leaves, so do you want to keep that specificity or collapse it into THATCH?

**Comment by xrotwang** [comment]
I'd say collapse it - as long as we don't run into a list with "THATCH" **and** "THATCH using a sago leaf".

**Comment by SimonGreenhill** [comment]
Nothing I've got has both THATCH and THATCH w/ sago, so I think THATCH is ok.

**Comment by LinguList** [comment]
Well, I'd say one should be careful about those. Why so? We once had a data where words for "thin" were collapsed, and it turned out to mess up everything, because there were three words for "thin": thin tea, thin body, thin leaf. With sago thatch, it may well be a compound, sago + thatch, and this might lead people to annotate cognates, but they are not between thatches, but between sagos. If you don't mind, Simon, I'll merge and take over, also adding a relation between "thatch" and "sago thatch". With the relations, you can still compare over nodes, but need to follow our underlying structure.

**Comment by SimonGreenhill** [comment]
All good, go for it 👍

**Comment by LinguList** [comment]
okay, done, I directly pushed to upstream.

**Pull request merged**
